pull_request_rules:
  - name: Signal automatic merge of PR
    conditions:
      - base=main
    actions:
        comment:
          message: |
              Hey @{{ author }} to cheeatos project
              Someone will take a look at you pull request

  - name: automatic merge for regularcontributors in main
    conditions:
      - base=main
      - label!=work-in-progress
      - author==dejanu
    actions:
      merge:
        method: merge